# Generated by Django 4.0.1 on 2022-01-18 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_cartitem_id_cartitem_auto_increment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='auto_increment_id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_date',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.datetime.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
