# Generated by Django 4.0.1 on 2022-01-18 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_remove_cartitem_auto_increment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_quantity',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
