# Generated by Django 4.0.1 on 2022-01-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_cartitem_product_date_cartitem_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_date',
        ),
    ]
