# Generated by Django 4.0.1 on 2022-01-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_remove_cartitem_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product_quantity',
        ),
    ]
